<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-27SQ7D8S" ignored="7" name="Default test" tests="1" failures="1" timestamp="14 Aug 2017 23:28:30 GMT" time="12.781" errors="0">
  <testcase name="Create_Proposal" time="0.0" classname="Sanity_Test.Test_Build2">
    <failure type="org.testng.TestNGException" message="
Data Provider public java.lang.Object[][] Sanity_Test.Test_Build2.dataProvider() must return either Object[][] or Iterator&amp;lt;Object&amp;gt;[], not class [[Ljava.lang.Object;">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] Sanity_Test.Test_Build2.dataProvider() must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Create_Proposal -->
  <testcase name="Sync_Cert_WithCA" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- Sync_Cert_WithCA -->
  <testcase name="Create_user_Account" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- Create_user_Account -->
  <testcase name="Send_Fulfillment_Email" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- Send_Fulfillment_Email -->
  <testcase name="Edit_Account_User" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- Edit_Account_User -->
  <testcase name="Admin_LogInValidation" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- Admin_LogInValidation -->
  <testcase name="Send_Change_Password_Request_Email" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- Send_Change_Password_Request_Email -->
  <testcase name="IssueProposal" time="0.0" classname="Sanity_Test.Test_Build2">
    <ignored/>
  </testcase> <!-- IssueProposal -->
</testsuite> <!-- Default test -->
